# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a12333aa054d3f418eec9bcc9aa3bc3290c37483e138b6b76ba536b780233a64f91fad4f4f0359b70e376b7302c80da3253326ec52df3bb81847b70790ad16f

test:
  secret_key_base: 8ae19b85e84b8c69b276b6dbb5a7b769c900c772ecede615996825ba63c3967d7cbcda0e9d5f9676f02f97379f8a5eaa793abcc9be35181ebad1aa4a664b6b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
